/**
 * FORJA · registro de imagenes
 *
 * ARCHIVO GENERADO por generar_registry.py. No lo edites a mano: copia tus
 * imagenes originales a media-fuente/img/<carpeta>/<id>.jpg y corre
 * `npm run imagenes` (optimiza a WebP y vuelve a correr este script).
 *
 * React Native no permite require() con ruta variable, por eso cada archivo
 * se declara aqui una vez. Lo que no este registrado se dibuja con un
 * marcador generado del id, asi que la app funciona con cero imagenes.
 *
 * Ejercicios y musculos tienen ademas una miniatura (`-mini`) para las
 * listas y rejillas: `fuenteMini` la devuelve, o la grande si no hay.
 */

type Registro = Record<string, number>;


/* ejercicios · 190 */
const IMG_EJERCICIOS: Registro = {
  'ex_1001': require('../../assets/img/ejercicios/ex_1001.webp'),
  'ex_1002': require('../../assets/img/ejercicios/ex_1002.webp'),
  'ex_1003': require('../../assets/img/ejercicios/ex_1003.webp'),
  'ex_1004': require('../../assets/img/ejercicios/ex_1004.webp'),
  'ex_1005': require('../../assets/img/ejercicios/ex_1005.webp'),
  'ex_1006': require('../../assets/img/ejercicios/ex_1006.webp'),
  'ex_1007': require('../../assets/img/ejercicios/ex_1007.webp'),
  'ex_1008': require('../../assets/img/ejercicios/ex_1008.webp'),
  'ex_1009': require('../../assets/img/ejercicios/ex_1009.webp'),
  'ex_1010': require('../../assets/img/ejercicios/ex_1010.webp'),
  'ex_1011': require('../../assets/img/ejercicios/ex_1011.webp'),
  'ex_1012': require('../../assets/img/ejercicios/ex_1012.webp'),
  'ex_1013': require('../../assets/img/ejercicios/ex_1013.webp'),
  'ex_1014': require('../../assets/img/ejercicios/ex_1014.webp'),
  'ex_1015': require('../../assets/img/ejercicios/ex_1015.webp'),
  'ex_1016': require('../../assets/img/ejercicios/ex_1016.webp'),
  'ex_1017': require('../../assets/img/ejercicios/ex_1017.webp'),
  'ex_1018': require('../../assets/img/ejercicios/ex_1018.webp'),
  'ex_1019': require('../../assets/img/ejercicios/ex_1019.webp'),
  'ex_1020': require('../../assets/img/ejercicios/ex_1020.webp'),
  'ex_1021': require('../../assets/img/ejercicios/ex_1021.webp'),
  'ex_1022': require('../../assets/img/ejercicios/ex_1022.webp'),
  'ex_1023': require('../../assets/img/ejercicios/ex_1023.webp'),
  'ex_1024': require('../../assets/img/ejercicios/ex_1024.webp'),
  'ex_1025': require('../../assets/img/ejercicios/ex_1025.webp'),
  'ex_1026': require('../../assets/img/ejercicios/ex_1026.webp'),
  'ex_1027': require('../../assets/img/ejercicios/ex_1027.webp'),
  'ex_1028': require('../../assets/img/ejercicios/ex_1028.webp'),
  'ex_1029': require('../../assets/img/ejercicios/ex_1029.webp'),
  'ex_1030': require('../../assets/img/ejercicios/ex_1030.webp'),
  'ex_2001': require('../../assets/img/ejercicios/ex_2001.webp'),
  'ex_2002': require('../../assets/img/ejercicios/ex_2002.webp'),
  'ex_2003': require('../../assets/img/ejercicios/ex_2003.webp'),
  'ex_2004': require('../../assets/img/ejercicios/ex_2004.webp'),
  'ex_2005': require('../../assets/img/ejercicios/ex_2005.webp'),
  'ex_2006': require('../../assets/img/ejercicios/ex_2006.webp'),
  'ex_2007': require('../../assets/img/ejercicios/ex_2007.webp'),
  'ex_2008': require('../../assets/img/ejercicios/ex_2008.webp'),
  'ex_2009': require('../../assets/img/ejercicios/ex_2009.webp'),
  'ex_2010': require('../../assets/img/ejercicios/ex_2010.webp'),
  'ex_2011': require('../../assets/img/ejercicios/ex_2011.webp'),
  'ex_2012': require('../../assets/img/ejercicios/ex_2012.webp'),
  'ex_2013': require('../../assets/img/ejercicios/ex_2013.webp'),
  'ex_2014': require('../../assets/img/ejercicios/ex_2014.webp'),
  'ex_2015': require('../../assets/img/ejercicios/ex_2015.webp'),
  'ex_2016': require('../../assets/img/ejercicios/ex_2016.webp'),
  'ex_2017': require('../../assets/img/ejercicios/ex_2017.webp'),
  'ex_2018': require('../../assets/img/ejercicios/ex_2018.webp'),
  'ex_2019': require('../../assets/img/ejercicios/ex_2019.webp'),
  'ex_2020': require('../../assets/img/ejercicios/ex_2020.webp'),
  'ex_3001': require('../../assets/img/ejercicios/ex_3001.webp'),
  'ex_3002': require('../../assets/img/ejercicios/ex_3002.webp'),
  'ex_3003': require('../../assets/img/ejercicios/ex_3003.webp'),
  'ex_3004': require('../../assets/img/ejercicios/ex_3004.webp'),
  'ex_3005': require('../../assets/img/ejercicios/ex_3005.webp'),
  'ex_3006': require('../../assets/img/ejercicios/ex_3006.webp'),
  'ex_3007': require('../../assets/img/ejercicios/ex_3007.webp'),
  'ex_3008': require('../../assets/img/ejercicios/ex_3008.webp'),
  'ex_3009': require('../../assets/img/ejercicios/ex_3009.webp'),
  'ex_3010': require('../../assets/img/ejercicios/ex_3010.webp'),
  'ex_3011': require('../../assets/img/ejercicios/ex_3011.webp'),
  'ex_3012': require('../../assets/img/ejercicios/ex_3012.webp'),
  'ex_3013': require('../../assets/img/ejercicios/ex_3013.webp'),
  'ex_3014': require('../../assets/img/ejercicios/ex_3014.webp'),
  'ex_3015': require('../../assets/img/ejercicios/ex_3015.webp'),
  'ex_3016': require('../../assets/img/ejercicios/ex_3016.webp'),
  'ex_3017': require('../../assets/img/ejercicios/ex_3017.webp'),
  'ex_3018': require('../../assets/img/ejercicios/ex_3018.webp'),
  'ex_3019': require('../../assets/img/ejercicios/ex_3019.webp'),
  'ex_3020': require('../../assets/img/ejercicios/ex_3020.webp'),
  'ex_4001': require('../../assets/img/ejercicios/ex_4001.webp'),
  'ex_4002': require('../../assets/img/ejercicios/ex_4002.webp'),
  'ex_4003': require('../../assets/img/ejercicios/ex_4003.webp'),
  'ex_4004': require('../../assets/img/ejercicios/ex_4004.webp'),
  'ex_4005': require('../../assets/img/ejercicios/ex_4005.webp'),
  'ex_4006': require('../../assets/img/ejercicios/ex_4006.webp'),
  'ex_4007': require('../../assets/img/ejercicios/ex_4007.webp'),
  'ex_4008': require('../../assets/img/ejercicios/ex_4008.webp'),
  'ex_4009': require('../../assets/img/ejercicios/ex_4009.webp'),
  'ex_4010': require('../../assets/img/ejercicios/ex_4010.webp'),
  'ex_4011': require('../../assets/img/ejercicios/ex_4011.webp'),
  'ex_4012': require('../../assets/img/ejercicios/ex_4012.webp'),
  'ex_4013': require('../../assets/img/ejercicios/ex_4013.webp'),
  'ex_4014': require('../../assets/img/ejercicios/ex_4014.webp'),
  'ex_4015': require('../../assets/img/ejercicios/ex_4015.webp'),
  'ex_4016': require('../../assets/img/ejercicios/ex_4016.webp'),
  'ex_4017': require('../../assets/img/ejercicios/ex_4017.webp'),
  'ex_4018': require('../../assets/img/ejercicios/ex_4018.webp'),
  'ex_4019': require('../../assets/img/ejercicios/ex_4019.webp'),
  'ex_4020': require('../../assets/img/ejercicios/ex_4020.webp'),
  'ex_4021': require('../../assets/img/ejercicios/ex_4021.webp'),
  'ex_4022': require('../../assets/img/ejercicios/ex_4022.webp'),
  'ex_5001': require('../../assets/img/ejercicios/ex_5001.webp'),
  'ex_5002': require('../../assets/img/ejercicios/ex_5002.webp'),
  'ex_5003': require('../../assets/img/ejercicios/ex_5003.webp'),
  'ex_5004': require('../../assets/img/ejercicios/ex_5004.webp'),
  'ex_5005': require('../../assets/img/ejercicios/ex_5005.webp'),
  'ex_5006': require('../../assets/img/ejercicios/ex_5006.webp'),
  'ex_5007': require('../../assets/img/ejercicios/ex_5007.webp'),
  'ex_5008': require('../../assets/img/ejercicios/ex_5008.webp'),
  'ex_5009': require('../../assets/img/ejercicios/ex_5009.webp'),
  'ex_5010': require('../../assets/img/ejercicios/ex_5010.webp'),
  'ex_5011': require('../../assets/img/ejercicios/ex_5011.webp'),
  'ex_5012': require('../../assets/img/ejercicios/ex_5012.webp'),
  'ex_5013': require('../../assets/img/ejercicios/ex_5013.webp'),
  'ex_5014': require('../../assets/img/ejercicios/ex_5014.webp'),
  'ex_5015': require('../../assets/img/ejercicios/ex_5015.webp'),
  'ex_5016': require('../../assets/img/ejercicios/ex_5016.webp'),
  'ex_5017': require('../../assets/img/ejercicios/ex_5017.webp'),
  'ex_5018': require('../../assets/img/ejercicios/ex_5018.webp'),
  'ex_5019': require('../../assets/img/ejercicios/ex_5019.webp'),
  'ex_5020': require('../../assets/img/ejercicios/ex_5020.webp'),
  'ex_5101': require('../../assets/img/ejercicios/ex_5101.webp'),
  'ex_5102': require('../../assets/img/ejercicios/ex_5102.webp'),
  'ex_5103': require('../../assets/img/ejercicios/ex_5103.webp'),
  'ex_5104': require('../../assets/img/ejercicios/ex_5104.webp'),
  'ex_5105': require('../../assets/img/ejercicios/ex_5105.webp'),
  'ex_5106': require('../../assets/img/ejercicios/ex_5106.webp'),
  'ex_5107': require('../../assets/img/ejercicios/ex_5107.webp'),
  'ex_5108': require('../../assets/img/ejercicios/ex_5108.webp'),
  'ex_5109': require('../../assets/img/ejercicios/ex_5109.webp'),
  'ex_5110': require('../../assets/img/ejercicios/ex_5110.webp'),
  'ex_5111': require('../../assets/img/ejercicios/ex_5111.webp'),
  'ex_6101': require('../../assets/img/ejercicios/ex_6101.webp'),
  'ex_6102': require('../../assets/img/ejercicios/ex_6102.webp'),
  'ex_6103': require('../../assets/img/ejercicios/ex_6103.webp'),
  'ex_6104': require('../../assets/img/ejercicios/ex_6104.webp'),
  'ex_6105': require('../../assets/img/ejercicios/ex_6105.webp'),
  'ex_6106': require('../../assets/img/ejercicios/ex_6106.webp'),
  'ex_6107': require('../../assets/img/ejercicios/ex_6107.webp'),
  'ex_6108': require('../../assets/img/ejercicios/ex_6108.webp'),
  'ex_6109': require('../../assets/img/ejercicios/ex_6109.webp'),
  'ex_6110': require('../../assets/img/ejercicios/ex_6110.webp'),
  'ex_6111': require('../../assets/img/ejercicios/ex_6111.webp'),
  'ex_6112': require('../../assets/img/ejercicios/ex_6112.webp'),
  'ex_6113': require('../../assets/img/ejercicios/ex_6113.webp'),
  'ex_6114': require('../../assets/img/ejercicios/ex_6114.webp'),
  'ex_6115': require('../../assets/img/ejercicios/ex_6115.webp'),
  'ex_6116': require('../../assets/img/ejercicios/ex_6116.webp'),
  'ex_6117': require('../../assets/img/ejercicios/ex_6117.webp'),
  'ex_6118': require('../../assets/img/ejercicios/ex_6118.webp'),
  'ex_6119': require('../../assets/img/ejercicios/ex_6119.webp'),
  'ex_6120': require('../../assets/img/ejercicios/ex_6120.webp'),
  'ex_6501': require('../../assets/img/ejercicios/ex_6501.webp'),
  'ex_6502': require('../../assets/img/ejercicios/ex_6502.webp'),
  'ex_6503': require('../../assets/img/ejercicios/ex_6503.webp'),
  'ex_6504': require('../../assets/img/ejercicios/ex_6504.webp'),
  'ex_6505': require('../../assets/img/ejercicios/ex_6505.webp'),
  'ex_6506': require('../../assets/img/ejercicios/ex_6506.webp'),
  'ex_6507': require('../../assets/img/ejercicios/ex_6507.webp'),
  'ex_6508': require('../../assets/img/ejercicios/ex_6508.webp'),
  'ex_6509': require('../../assets/img/ejercicios/ex_6509.webp'),
  'ex_6510': require('../../assets/img/ejercicios/ex_6510.webp'),
  'ex_6511': require('../../assets/img/ejercicios/ex_6511.webp'),
  'ex_6512': require('../../assets/img/ejercicios/ex_6512.webp'),
  'ex_7001': require('../../assets/img/ejercicios/ex_7001.webp'),
  'ex_7002': require('../../assets/img/ejercicios/ex_7002.webp'),
  'ex_7003': require('../../assets/img/ejercicios/ex_7003.webp'),
  'ex_7004': require('../../assets/img/ejercicios/ex_7004.webp'),
  'ex_7005': require('../../assets/img/ejercicios/ex_7005.webp'),
  'ex_7006': require('../../assets/img/ejercicios/ex_7006.webp'),
  'ex_7007': require('../../assets/img/ejercicios/ex_7007.webp'),
  'ex_7008': require('../../assets/img/ejercicios/ex_7008.webp'),
  'ex_7009': require('../../assets/img/ejercicios/ex_7009.webp'),
  'ex_7010': require('../../assets/img/ejercicios/ex_7010.webp'),
  'ex_7011': require('../../assets/img/ejercicios/ex_7011.webp'),
  'ex_7012': require('../../assets/img/ejercicios/ex_7012.webp'),
  'ex_7013': require('../../assets/img/ejercicios/ex_7013.webp'),
  'ex_7014': require('../../assets/img/ejercicios/ex_7014.webp'),
  'ex_7015': require('../../assets/img/ejercicios/ex_7015.webp'),
  'ex_7016': require('../../assets/img/ejercicios/ex_7016.webp'),
  'ex_7017': require('../../assets/img/ejercicios/ex_7017.webp'),
  'ex_7018': require('../../assets/img/ejercicios/ex_7018.webp'),
  'ex_7019': require('../../assets/img/ejercicios/ex_7019.webp'),
  'ex_7020': require('../../assets/img/ejercicios/ex_7020.webp'),
  'ex_8001': require('../../assets/img/ejercicios/ex_8001.webp'),
  'ex_8002': require('../../assets/img/ejercicios/ex_8002.webp'),
  'ex_8003': require('../../assets/img/ejercicios/ex_8003.webp'),
  'ex_8004': require('../../assets/img/ejercicios/ex_8004.webp'),
  'ex_8005': require('../../assets/img/ejercicios/ex_8005.webp'),
  'ex_8006': require('../../assets/img/ejercicios/ex_8006.webp'),
  'ex_8007': require('../../assets/img/ejercicios/ex_8007.webp'),
  'ex_8008': require('../../assets/img/ejercicios/ex_8008.webp'),
  'ex_8009': require('../../assets/img/ejercicios/ex_8009.webp'),
  'ex_8010': require('../../assets/img/ejercicios/ex_8010.webp'),
  'ex_8011': require('../../assets/img/ejercicios/ex_8011.webp'),
  'ex_8012': require('../../assets/img/ejercicios/ex_8012.webp'),
  'ex_8013': require('../../assets/img/ejercicios/ex_8013.webp'),
  'ex_8014': require('../../assets/img/ejercicios/ex_8014.webp'),
  'ex_8015': require('../../assets/img/ejercicios/ex_8015.webp'),
};

/* musculos · 52 */
const IMG_MUSCULOS: Registro = {
  'aductores': require('../../assets/img/musculos/aductores.webp'),
  'antebrazo': require('../../assets/img/musculos/antebrazo.webp'),
  'biceps': require('../../assets/img/musculos/biceps.webp'),
  'braquial': require('../../assets/img/musculos/braquial.webp'),
  'buccinador': require('../../assets/img/musculos/buccinador.webp'),
  'cigomaticos': require('../../assets/img/musculos/cigomaticos.webp'),
  'core': require('../../assets/img/musculos/core.webp'),
  'cuadriceps': require('../../assets/img/musculos/cuadriceps.webp'),
  'cuello_flexores': require('../../assets/img/musculos/cuello_flexores.webp'),
  'deltoide_anterior': require('../../assets/img/musculos/deltoide_anterior.webp'),
  'deltoide_lateral': require('../../assets/img/musculos/deltoide_lateral.webp'),
  'deltoide_posterior': require('../../assets/img/musculos/deltoide_posterior.webp'),
  'depresor_labio': require('../../assets/img/musculos/depresor_labio.webp'),
  'diafragma': require('../../assets/img/musculos/diafragma.webp'),
  'digastrico': require('../../assets/img/musculos/digastrico.webp'),
  'dorsal_ancho': require('../../assets/img/musculos/dorsal_ancho.webp'),
  'erectores_espinales': require('../../assets/img/musculos/erectores_espinales.webp'),
  'esternocleidomastoideo': require('../../assets/img/musculos/esternocleidomastoideo.webp'),
  'extensores_cuello': require('../../assets/img/musculos/extensores_cuello.webp'),
  'flexor_cadera': require('../../assets/img/musculos/flexor_cadera.webp'),
  'gemelos': require('../../assets/img/musculos/gemelos.webp'),
  'gluteo_mayor': require('../../assets/img/musculos/gluteo_mayor.webp'),
  'gluteo_medio': require('../../assets/img/musculos/gluteo_medio.webp'),
  'gluteo_menor': require('../../assets/img/musculos/gluteo_menor.webp'),
  'isquiotibiales': require('../../assets/img/musculos/isquiotibiales.webp'),
  'lengua': require('../../assets/img/musculos/lengua.webp'),
  'manguito_rotador': require('../../assets/img/musculos/manguito_rotador.webp'),
  'masetero': require('../../assets/img/musculos/masetero.webp'),
  'multifidos': require('../../assets/img/musculos/multifidos.webp'),
  'oblicuo_externo': require('../../assets/img/musculos/oblicuo_externo.webp'),
  'oblicuo_interno': require('../../assets/img/musculos/oblicuo_interno.webp'),
  'orbicular_labios': require('../../assets/img/musculos/orbicular_labios.webp'),
  'pectoral_mayor': require('../../assets/img/musculos/pectoral_mayor.webp'),
  'pectoral_menor': require('../../assets/img/musculos/pectoral_menor.webp'),
  'pie_intrinsecos': require('../../assets/img/musculos/pie_intrinsecos.webp'),
  'platisma': require('../../assets/img/musculos/platisma.webp'),
  'pterigoideos': require('../../assets/img/musculos/pterigoideos.webp'),
  'recto_abdominal': require('../../assets/img/musculos/recto_abdominal.webp'),
  'recto_femoral': require('../../assets/img/musculos/recto_femoral.webp'),
  'redondo_mayor': require('../../assets/img/musculos/redondo_mayor.webp'),
  'romboides': require('../../assets/img/musculos/romboides.webp'),
  'serrato_anterior': require('../../assets/img/musculos/serrato_anterior.webp'),
  'soleo': require('../../assets/img/musculos/soleo.webp'),
  'suelo_pelvico': require('../../assets/img/musculos/suelo_pelvico.webp'),
  'temporal': require('../../assets/img/musculos/temporal.webp'),
  'tensor_fascia_lata': require('../../assets/img/musculos/tensor_fascia_lata.webp'),
  'tibial_anterior': require('../../assets/img/musculos/tibial_anterior.webp'),
  'transverso_abdominal': require('../../assets/img/musculos/transverso_abdominal.webp'),
  'trapecio_inferior': require('../../assets/img/musculos/trapecio_inferior.webp'),
  'trapecio_medio': require('../../assets/img/musculos/trapecio_medio.webp'),
  'trapecio_superior': require('../../assets/img/musculos/trapecio_superior.webp'),
  'triceps': require('../../assets/img/musculos/triceps.webp'),
};

/* rutinas · 30 */
const IMG_RUTINAS: Registro = {
  'rt_001': require('../../assets/img/rutinas/rt_001.webp'),
  'rt_002': require('../../assets/img/rutinas/rt_002.webp'),
  'rt_003': require('../../assets/img/rutinas/rt_003.webp'),
  'rt_004': require('../../assets/img/rutinas/rt_004.webp'),
  'rt_005': require('../../assets/img/rutinas/rt_005.webp'),
  'rt_006': require('../../assets/img/rutinas/rt_006.webp'),
  'rt_007': require('../../assets/img/rutinas/rt_007.webp'),
  'rt_008': require('../../assets/img/rutinas/rt_008.webp'),
  'rt_009': require('../../assets/img/rutinas/rt_009.webp'),
  'rt_010': require('../../assets/img/rutinas/rt_010.webp'),
  'rt_011': require('../../assets/img/rutinas/rt_011.webp'),
  'rt_012': require('../../assets/img/rutinas/rt_012.webp'),
  'rt_013': require('../../assets/img/rutinas/rt_013.webp'),
  'rt_014': require('../../assets/img/rutinas/rt_014.webp'),
  'rt_015': require('../../assets/img/rutinas/rt_015.webp'),
  'rt_016': require('../../assets/img/rutinas/rt_016.webp'),
  'rt_017': require('../../assets/img/rutinas/rt_017.webp'),
  'rt_018': require('../../assets/img/rutinas/rt_018.webp'),
  'rt_019': require('../../assets/img/rutinas/rt_019.webp'),
  'rt_020': require('../../assets/img/rutinas/rt_020.webp'),
  'rt_021': require('../../assets/img/rutinas/rt_021.webp'),
  'rt_022': require('../../assets/img/rutinas/rt_022.webp'),
  'rt_023': require('../../assets/img/rutinas/rt_023.webp'),
  'rt_024': require('../../assets/img/rutinas/rt_024.webp'),
  'rt_025': require('../../assets/img/rutinas/rt_025.webp'),
  'rt_026': require('../../assets/img/rutinas/rt_026.webp'),
  'rt_027': require('../../assets/img/rutinas/rt_027.webp'),
  'rt_028': require('../../assets/img/rutinas/rt_028.webp'),
  'rt_029': require('../../assets/img/rutinas/rt_029.webp'),
  'rt_030': require('../../assets/img/rutinas/rt_030.webp'),
};

/* programas · 12 */
const IMG_PROGRAMAS: Registro = {
  'pg_001': require('../../assets/img/programas/pg_001.webp'),
  'pg_002': require('../../assets/img/programas/pg_002.webp'),
  'pg_003': require('../../assets/img/programas/pg_003.webp'),
  'pg_004': require('../../assets/img/programas/pg_004.webp'),
  'pg_005': require('../../assets/img/programas/pg_005.webp'),
  'pg_006': require('../../assets/img/programas/pg_006.webp'),
  'pg_007': require('../../assets/img/programas/pg_007.webp'),
  'pg_008': require('../../assets/img/programas/pg_008.webp'),
  'pg_009': require('../../assets/img/programas/pg_009.webp'),
  'pg_010': require('../../assets/img/programas/pg_010.webp'),
  'pg_011': require('../../assets/img/programas/pg_011.webp'),
  'pg_012': require('../../assets/img/programas/pg_012.webp'),
};

/* tips · 52 */
const IMG_TIPS: Registro = {
  'nut_001': require('../../assets/img/tips/nut_001.webp'),
  'nut_002': require('../../assets/img/tips/nut_002.webp'),
  'nut_003': require('../../assets/img/tips/nut_003.webp'),
  'nut_004': require('../../assets/img/tips/nut_004.webp'),
  'nut_005': require('../../assets/img/tips/nut_005.webp'),
  'nut_006': require('../../assets/img/tips/nut_006.webp'),
  'nut_007': require('../../assets/img/tips/nut_007.webp'),
  'nut_009': require('../../assets/img/tips/nut_009.webp'),
  'nut_010': require('../../assets/img/tips/nut_010.webp'),
  'nut_011': require('../../assets/img/tips/nut_011.webp'),
  'nut_012': require('../../assets/img/tips/nut_012.webp'),
  'nut_013': require('../../assets/img/tips/nut_013.webp'),
  'nut_014': require('../../assets/img/tips/nut_014.webp'),
  'nut_015': require('../../assets/img/tips/nut_015.webp'),
  'tip_001': require('../../assets/img/tips/tip_001.webp'),
  'tip_002': require('../../assets/img/tips/tip_002.webp'),
  'tip_003': require('../../assets/img/tips/tip_003.webp'),
  'tip_004': require('../../assets/img/tips/tip_004.webp'),
  'tip_005': require('../../assets/img/tips/tip_005.webp'),
  'tip_006': require('../../assets/img/tips/tip_006.webp'),
  'tip_007': require('../../assets/img/tips/tip_007.webp'),
  'tip_008': require('../../assets/img/tips/tip_008.webp'),
  'tip_009': require('../../assets/img/tips/tip_009.webp'),
  'tip_010': require('../../assets/img/tips/tip_010.webp'),
  'tip_011': require('../../assets/img/tips/tip_011.webp'),
  'tip_012': require('../../assets/img/tips/tip_012.webp'),
  'tip_013': require('../../assets/img/tips/tip_013.webp'),
  'tip_014': require('../../assets/img/tips/tip_014.webp'),
  'tip_015': require('../../assets/img/tips/tip_015.webp'),
  'tip_016': require('../../assets/img/tips/tip_016.webp'),
  'tip_017': require('../../assets/img/tips/tip_017.webp'),
  'tip_018': require('../../assets/img/tips/tip_018.webp'),
  'tip_019': require('../../assets/img/tips/tip_019.webp'),
  'tip_020': require('../../assets/img/tips/tip_020.webp'),
  'tip_021': require('../../assets/img/tips/tip_021.webp'),
  'tip_022': require('../../assets/img/tips/tip_022.webp'),
  'tip_023': require('../../assets/img/tips/tip_023.webp'),
  'tip_024': require('../../assets/img/tips/tip_024.webp'),
  'tip_025': require('../../assets/img/tips/tip_025.webp'),
  'tip_026': require('../../assets/img/tips/tip_026.webp'),
  'tip_027': require('../../assets/img/tips/tip_027.webp'),
  'tip_028': require('../../assets/img/tips/tip_028.webp'),
  'tip_029': require('../../assets/img/tips/tip_029.webp'),
  'tip_030': require('../../assets/img/tips/tip_030.webp'),
  'tip_031': require('../../assets/img/tips/tip_031.webp'),
  'tip_032': require('../../assets/img/tips/tip_032.webp'),
  'tip_033': require('../../assets/img/tips/tip_033.webp'),
  'tip_034': require('../../assets/img/tips/tip_034.webp'),
  'tip_035': require('../../assets/img/tips/tip_035.webp'),
  'tip_036': require('../../assets/img/tips/tip_036.webp'),
  'tip_037': require('../../assets/img/tips/tip_037.webp'),
  'tip_038': require('../../assets/img/tips/tip_038.webp'),
};

/* mitos · 20 */
const IMG_MITOS: Registro = {
  'myth_001': require('../../assets/img/mitos/myth_001.webp'),
  'myth_002': require('../../assets/img/mitos/myth_002.webp'),
  'myth_003': require('../../assets/img/mitos/myth_003.webp'),
  'myth_004': require('../../assets/img/mitos/myth_004.webp'),
  'myth_005': require('../../assets/img/mitos/myth_005.webp'),
  'myth_006': require('../../assets/img/mitos/myth_006.webp'),
  'myth_007': require('../../assets/img/mitos/myth_007.webp'),
  'myth_008': require('../../assets/img/mitos/myth_008.webp'),
  'myth_009': require('../../assets/img/mitos/myth_009.webp'),
  'myth_010': require('../../assets/img/mitos/myth_010.webp'),
  'myth_011': require('../../assets/img/mitos/myth_011.webp'),
  'myth_012': require('../../assets/img/mitos/myth_012.webp'),
  'myth_013': require('../../assets/img/mitos/myth_013.webp'),
  'myth_014': require('../../assets/img/mitos/myth_014.webp'),
  'myth_015': require('../../assets/img/mitos/myth_015.webp'),
  'myth_016': require('../../assets/img/mitos/myth_016.webp'),
  'myth_017': require('../../assets/img/mitos/myth_017.webp'),
  'myth_018': require('../../assets/img/mitos/myth_018.webp'),
  'myth_019': require('../../assets/img/mitos/myth_019.webp'),
  'myth_020': require('../../assets/img/mitos/myth_020.webp'),
};

/* motivacion · 21 */
const IMG_MOTIVACION: Registro = {
  'mot_01': require('../../assets/img/motivacion/mot_01.webp'),
  'mot_02': require('../../assets/img/motivacion/mot_02.webp'),
  'mot_03': require('../../assets/img/motivacion/mot_03.webp'),
  'mot_04': require('../../assets/img/motivacion/mot_04.webp'),
  'mot_05': require('../../assets/img/motivacion/mot_05.webp'),
  'mot_06': require('../../assets/img/motivacion/mot_06.webp'),
  'mot_07': require('../../assets/img/motivacion/mot_07.webp'),
  'mot_08': require('../../assets/img/motivacion/mot_08.webp'),
  'mot_09': require('../../assets/img/motivacion/mot_09.webp'),
  'mot_10': require('../../assets/img/motivacion/mot_10.webp'),
  'mot_11': require('../../assets/img/motivacion/mot_11.webp'),
  'mot_12': require('../../assets/img/motivacion/mot_12.webp'),
  'mot_13': require('../../assets/img/motivacion/mot_13.webp'),
  'mot_14': require('../../assets/img/motivacion/mot_14.webp'),
  'mot_15': require('../../assets/img/motivacion/mot_15.webp'),
  'mot_16': require('../../assets/img/motivacion/mot_16.webp'),
  'mot_17': require('../../assets/img/motivacion/mot_17.webp'),
  'mot_18': require('../../assets/img/motivacion/mot_18.webp'),
  'mot_19': require('../../assets/img/motivacion/mot_19.webp'),
  'mot_20': require('../../assets/img/motivacion/mot_20.webp'),
  'mot_21': require('../../assets/img/motivacion/mot_21.webp'),
};

/* fondos · 5 */
const IMG_FONDOS: Registro = {
  'bienvenida': require('../../assets/img/fondos/bienvenida.webp'),
  'intro_01': require('../../assets/img/fondos/intro_01.webp'),
  'intro_02': require('../../assets/img/fondos/intro_02.webp'),
  'intro_03': require('../../assets/img/fondos/intro_03.webp'),
  'intro_04': require('../../assets/img/fondos/intro_04.webp'),
};

/* ejercicios-mini · 190 */
const IMG_EJERCICIOS_MINI: Registro = {
  'ex_1001': require('../../assets/img/ejercicios-mini/ex_1001.webp'),
  'ex_1002': require('../../assets/img/ejercicios-mini/ex_1002.webp'),
  'ex_1003': require('../../assets/img/ejercicios-mini/ex_1003.webp'),
  'ex_1004': require('../../assets/img/ejercicios-mini/ex_1004.webp'),
  'ex_1005': require('../../assets/img/ejercicios-mini/ex_1005.webp'),
  'ex_1006': require('../../assets/img/ejercicios-mini/ex_1006.webp'),
  'ex_1007': require('../../assets/img/ejercicios-mini/ex_1007.webp'),
  'ex_1008': require('../../assets/img/ejercicios-mini/ex_1008.webp'),
  'ex_1009': require('../../assets/img/ejercicios-mini/ex_1009.webp'),
  'ex_1010': require('../../assets/img/ejercicios-mini/ex_1010.webp'),
  'ex_1011': require('../../assets/img/ejercicios-mini/ex_1011.webp'),
  'ex_1012': require('../../assets/img/ejercicios-mini/ex_1012.webp'),
  'ex_1013': require('../../assets/img/ejercicios-mini/ex_1013.webp'),
  'ex_1014': require('../../assets/img/ejercicios-mini/ex_1014.webp'),
  'ex_1015': require('../../assets/img/ejercicios-mini/ex_1015.webp'),
  'ex_1016': require('../../assets/img/ejercicios-mini/ex_1016.webp'),
  'ex_1017': require('../../assets/img/ejercicios-mini/ex_1017.webp'),
  'ex_1018': require('../../assets/img/ejercicios-mini/ex_1018.webp'),
  'ex_1019': require('../../assets/img/ejercicios-mini/ex_1019.webp'),
  'ex_1020': require('../../assets/img/ejercicios-mini/ex_1020.webp'),
  'ex_1021': require('../../assets/img/ejercicios-mini/ex_1021.webp'),
  'ex_1022': require('../../assets/img/ejercicios-mini/ex_1022.webp'),
  'ex_1023': require('../../assets/img/ejercicios-mini/ex_1023.webp'),
  'ex_1024': require('../../assets/img/ejercicios-mini/ex_1024.webp'),
  'ex_1025': require('../../assets/img/ejercicios-mini/ex_1025.webp'),
  'ex_1026': require('../../assets/img/ejercicios-mini/ex_1026.webp'),
  'ex_1027': require('../../assets/img/ejercicios-mini/ex_1027.webp'),
  'ex_1028': require('../../assets/img/ejercicios-mini/ex_1028.webp'),
  'ex_1029': require('../../assets/img/ejercicios-mini/ex_1029.webp'),
  'ex_1030': require('../../assets/img/ejercicios-mini/ex_1030.webp'),
  'ex_2001': require('../../assets/img/ejercicios-mini/ex_2001.webp'),
  'ex_2002': require('../../assets/img/ejercicios-mini/ex_2002.webp'),
  'ex_2003': require('../../assets/img/ejercicios-mini/ex_2003.webp'),
  'ex_2004': require('../../assets/img/ejercicios-mini/ex_2004.webp'),
  'ex_2005': require('../../assets/img/ejercicios-mini/ex_2005.webp'),
  'ex_2006': require('../../assets/img/ejercicios-mini/ex_2006.webp'),
  'ex_2007': require('../../assets/img/ejercicios-mini/ex_2007.webp'),
  'ex_2008': require('../../assets/img/ejercicios-mini/ex_2008.webp'),
  'ex_2009': require('../../assets/img/ejercicios-mini/ex_2009.webp'),
  'ex_2010': require('../../assets/img/ejercicios-mini/ex_2010.webp'),
  'ex_2011': require('../../assets/img/ejercicios-mini/ex_2011.webp'),
  'ex_2012': require('../../assets/img/ejercicios-mini/ex_2012.webp'),
  'ex_2013': require('../../assets/img/ejercicios-mini/ex_2013.webp'),
  'ex_2014': require('../../assets/img/ejercicios-mini/ex_2014.webp'),
  'ex_2015': require('../../assets/img/ejercicios-mini/ex_2015.webp'),
  'ex_2016': require('../../assets/img/ejercicios-mini/ex_2016.webp'),
  'ex_2017': require('../../assets/img/ejercicios-mini/ex_2017.webp'),
  'ex_2018': require('../../assets/img/ejercicios-mini/ex_2018.webp'),
  'ex_2019': require('../../assets/img/ejercicios-mini/ex_2019.webp'),
  'ex_2020': require('../../assets/img/ejercicios-mini/ex_2020.webp'),
  'ex_3001': require('../../assets/img/ejercicios-mini/ex_3001.webp'),
  'ex_3002': require('../../assets/img/ejercicios-mini/ex_3002.webp'),
  'ex_3003': require('../../assets/img/ejercicios-mini/ex_3003.webp'),
  'ex_3004': require('../../assets/img/ejercicios-mini/ex_3004.webp'),
  'ex_3005': require('../../assets/img/ejercicios-mini/ex_3005.webp'),
  'ex_3006': require('../../assets/img/ejercicios-mini/ex_3006.webp'),
  'ex_3007': require('../../assets/img/ejercicios-mini/ex_3007.webp'),
  'ex_3008': require('../../assets/img/ejercicios-mini/ex_3008.webp'),
  'ex_3009': require('../../assets/img/ejercicios-mini/ex_3009.webp'),
  'ex_3010': require('../../assets/img/ejercicios-mini/ex_3010.webp'),
  'ex_3011': require('../../assets/img/ejercicios-mini/ex_3011.webp'),
  'ex_3012': require('../../assets/img/ejercicios-mini/ex_3012.webp'),
  'ex_3013': require('../../assets/img/ejercicios-mini/ex_3013.webp'),
  'ex_3014': require('../../assets/img/ejercicios-mini/ex_3014.webp'),
  'ex_3015': require('../../assets/img/ejercicios-mini/ex_3015.webp'),
  'ex_3016': require('../../assets/img/ejercicios-mini/ex_3016.webp'),
  'ex_3017': require('../../assets/img/ejercicios-mini/ex_3017.webp'),
  'ex_3018': require('../../assets/img/ejercicios-mini/ex_3018.webp'),
  'ex_3019': require('../../assets/img/ejercicios-mini/ex_3019.webp'),
  'ex_3020': require('../../assets/img/ejercicios-mini/ex_3020.webp'),
  'ex_4001': require('../../assets/img/ejercicios-mini/ex_4001.webp'),
  'ex_4002': require('../../assets/img/ejercicios-mini/ex_4002.webp'),
  'ex_4003': require('../../assets/img/ejercicios-mini/ex_4003.webp'),
  'ex_4004': require('../../assets/img/ejercicios-mini/ex_4004.webp'),
  'ex_4005': require('../../assets/img/ejercicios-mini/ex_4005.webp'),
  'ex_4006': require('../../assets/img/ejercicios-mini/ex_4006.webp'),
  'ex_4007': require('../../assets/img/ejercicios-mini/ex_4007.webp'),
  'ex_4008': require('../../assets/img/ejercicios-mini/ex_4008.webp'),
  'ex_4009': require('../../assets/img/ejercicios-mini/ex_4009.webp'),
  'ex_4010': require('../../assets/img/ejercicios-mini/ex_4010.webp'),
  'ex_4011': require('../../assets/img/ejercicios-mini/ex_4011.webp'),
  'ex_4012': require('../../assets/img/ejercicios-mini/ex_4012.webp'),
  'ex_4013': require('../../assets/img/ejercicios-mini/ex_4013.webp'),
  'ex_4014': require('../../assets/img/ejercicios-mini/ex_4014.webp'),
  'ex_4015': require('../../assets/img/ejercicios-mini/ex_4015.webp'),
  'ex_4016': require('../../assets/img/ejercicios-mini/ex_4016.webp'),
  'ex_4017': require('../../assets/img/ejercicios-mini/ex_4017.webp'),
  'ex_4018': require('../../assets/img/ejercicios-mini/ex_4018.webp'),
  'ex_4019': require('../../assets/img/ejercicios-mini/ex_4019.webp'),
  'ex_4020': require('../../assets/img/ejercicios-mini/ex_4020.webp'),
  'ex_4021': require('../../assets/img/ejercicios-mini/ex_4021.webp'),
  'ex_4022': require('../../assets/img/ejercicios-mini/ex_4022.webp'),
  'ex_5001': require('../../assets/img/ejercicios-mini/ex_5001.webp'),
  'ex_5002': require('../../assets/img/ejercicios-mini/ex_5002.webp'),
  'ex_5003': require('../../assets/img/ejercicios-mini/ex_5003.webp'),
  'ex_5004': require('../../assets/img/ejercicios-mini/ex_5004.webp'),
  'ex_5005': require('../../assets/img/ejercicios-mini/ex_5005.webp'),
  'ex_5006': require('../../assets/img/ejercicios-mini/ex_5006.webp'),
  'ex_5007': require('../../assets/img/ejercicios-mini/ex_5007.webp'),
  'ex_5008': require('../../assets/img/ejercicios-mini/ex_5008.webp'),
  'ex_5009': require('../../assets/img/ejercicios-mini/ex_5009.webp'),
  'ex_5010': require('../../assets/img/ejercicios-mini/ex_5010.webp'),
  'ex_5011': require('../../assets/img/ejercicios-mini/ex_5011.webp'),
  'ex_5012': require('../../assets/img/ejercicios-mini/ex_5012.webp'),
  'ex_5013': require('../../assets/img/ejercicios-mini/ex_5013.webp'),
  'ex_5014': require('../../assets/img/ejercicios-mini/ex_5014.webp'),
  'ex_5015': require('../../assets/img/ejercicios-mini/ex_5015.webp'),
  'ex_5016': require('../../assets/img/ejercicios-mini/ex_5016.webp'),
  'ex_5017': require('../../assets/img/ejercicios-mini/ex_5017.webp'),
  'ex_5018': require('../../assets/img/ejercicios-mini/ex_5018.webp'),
  'ex_5019': require('../../assets/img/ejercicios-mini/ex_5019.webp'),
  'ex_5020': require('../../assets/img/ejercicios-mini/ex_5020.webp'),
  'ex_5101': require('../../assets/img/ejercicios-mini/ex_5101.webp'),
  'ex_5102': require('../../assets/img/ejercicios-mini/ex_5102.webp'),
  'ex_5103': require('../../assets/img/ejercicios-mini/ex_5103.webp'),
  'ex_5104': require('../../assets/img/ejercicios-mini/ex_5104.webp'),
  'ex_5105': require('../../assets/img/ejercicios-mini/ex_5105.webp'),
  'ex_5106': require('../../assets/img/ejercicios-mini/ex_5106.webp'),
  'ex_5107': require('../../assets/img/ejercicios-mini/ex_5107.webp'),
  'ex_5108': require('../../assets/img/ejercicios-mini/ex_5108.webp'),
  'ex_5109': require('../../assets/img/ejercicios-mini/ex_5109.webp'),
  'ex_5110': require('../../assets/img/ejercicios-mini/ex_5110.webp'),
  'ex_5111': require('../../assets/img/ejercicios-mini/ex_5111.webp'),
  'ex_6101': require('../../assets/img/ejercicios-mini/ex_6101.webp'),
  'ex_6102': require('../../assets/img/ejercicios-mini/ex_6102.webp'),
  'ex_6103': require('../../assets/img/ejercicios-mini/ex_6103.webp'),
  'ex_6104': require('../../assets/img/ejercicios-mini/ex_6104.webp'),
  'ex_6105': require('../../assets/img/ejercicios-mini/ex_6105.webp'),
  'ex_6106': require('../../assets/img/ejercicios-mini/ex_6106.webp'),
  'ex_6107': require('../../assets/img/ejercicios-mini/ex_6107.webp'),
  'ex_6108': require('../../assets/img/ejercicios-mini/ex_6108.webp'),
  'ex_6109': require('../../assets/img/ejercicios-mini/ex_6109.webp'),
  'ex_6110': require('../../assets/img/ejercicios-mini/ex_6110.webp'),
  'ex_6111': require('../../assets/img/ejercicios-mini/ex_6111.webp'),
  'ex_6112': require('../../assets/img/ejercicios-mini/ex_6112.webp'),
  'ex_6113': require('../../assets/img/ejercicios-mini/ex_6113.webp'),
  'ex_6114': require('../../assets/img/ejercicios-mini/ex_6114.webp'),
  'ex_6115': require('../../assets/img/ejercicios-mini/ex_6115.webp'),
  'ex_6116': require('../../assets/img/ejercicios-mini/ex_6116.webp'),
  'ex_6117': require('../../assets/img/ejercicios-mini/ex_6117.webp'),
  'ex_6118': require('../../assets/img/ejercicios-mini/ex_6118.webp'),
  'ex_6119': require('../../assets/img/ejercicios-mini/ex_6119.webp'),
  'ex_6120': require('../../assets/img/ejercicios-mini/ex_6120.webp'),
  'ex_6501': require('../../assets/img/ejercicios-mini/ex_6501.webp'),
  'ex_6502': require('../../assets/img/ejercicios-mini/ex_6502.webp'),
  'ex_6503': require('../../assets/img/ejercicios-mini/ex_6503.webp'),
  'ex_6504': require('../../assets/img/ejercicios-mini/ex_6504.webp'),
  'ex_6505': require('../../assets/img/ejercicios-mini/ex_6505.webp'),
  'ex_6506': require('../../assets/img/ejercicios-mini/ex_6506.webp'),
  'ex_6507': require('../../assets/img/ejercicios-mini/ex_6507.webp'),
  'ex_6508': require('../../assets/img/ejercicios-mini/ex_6508.webp'),
  'ex_6509': require('../../assets/img/ejercicios-mini/ex_6509.webp'),
  'ex_6510': require('../../assets/img/ejercicios-mini/ex_6510.webp'),
  'ex_6511': require('../../assets/img/ejercicios-mini/ex_6511.webp'),
  'ex_6512': require('../../assets/img/ejercicios-mini/ex_6512.webp'),
  'ex_7001': require('../../assets/img/ejercicios-mini/ex_7001.webp'),
  'ex_7002': require('../../assets/img/ejercicios-mini/ex_7002.webp'),
  'ex_7003': require('../../assets/img/ejercicios-mini/ex_7003.webp'),
  'ex_7004': require('../../assets/img/ejercicios-mini/ex_7004.webp'),
  'ex_7005': require('../../assets/img/ejercicios-mini/ex_7005.webp'),
  'ex_7006': require('../../assets/img/ejercicios-mini/ex_7006.webp'),
  'ex_7007': require('../../assets/img/ejercicios-mini/ex_7007.webp'),
  'ex_7008': require('../../assets/img/ejercicios-mini/ex_7008.webp'),
  'ex_7009': require('../../assets/img/ejercicios-mini/ex_7009.webp'),
  'ex_7010': require('../../assets/img/ejercicios-mini/ex_7010.webp'),
  'ex_7011': require('../../assets/img/ejercicios-mini/ex_7011.webp'),
  'ex_7012': require('../../assets/img/ejercicios-mini/ex_7012.webp'),
  'ex_7013': require('../../assets/img/ejercicios-mini/ex_7013.webp'),
  'ex_7014': require('../../assets/img/ejercicios-mini/ex_7014.webp'),
  'ex_7015': require('../../assets/img/ejercicios-mini/ex_7015.webp'),
  'ex_7016': require('../../assets/img/ejercicios-mini/ex_7016.webp'),
  'ex_7017': require('../../assets/img/ejercicios-mini/ex_7017.webp'),
  'ex_7018': require('../../assets/img/ejercicios-mini/ex_7018.webp'),
  'ex_7019': require('../../assets/img/ejercicios-mini/ex_7019.webp'),
  'ex_7020': require('../../assets/img/ejercicios-mini/ex_7020.webp'),
  'ex_8001': require('../../assets/img/ejercicios-mini/ex_8001.webp'),
  'ex_8002': require('../../assets/img/ejercicios-mini/ex_8002.webp'),
  'ex_8003': require('../../assets/img/ejercicios-mini/ex_8003.webp'),
  'ex_8004': require('../../assets/img/ejercicios-mini/ex_8004.webp'),
  'ex_8005': require('../../assets/img/ejercicios-mini/ex_8005.webp'),
  'ex_8006': require('../../assets/img/ejercicios-mini/ex_8006.webp'),
  'ex_8007': require('../../assets/img/ejercicios-mini/ex_8007.webp'),
  'ex_8008': require('../../assets/img/ejercicios-mini/ex_8008.webp'),
  'ex_8009': require('../../assets/img/ejercicios-mini/ex_8009.webp'),
  'ex_8010': require('../../assets/img/ejercicios-mini/ex_8010.webp'),
  'ex_8011': require('../../assets/img/ejercicios-mini/ex_8011.webp'),
  'ex_8012': require('../../assets/img/ejercicios-mini/ex_8012.webp'),
  'ex_8013': require('../../assets/img/ejercicios-mini/ex_8013.webp'),
  'ex_8014': require('../../assets/img/ejercicios-mini/ex_8014.webp'),
  'ex_8015': require('../../assets/img/ejercicios-mini/ex_8015.webp'),
};

/* musculos-mini · 52 */
const IMG_MUSCULOS_MINI: Registro = {
  'aductores': require('../../assets/img/musculos-mini/aductores.webp'),
  'antebrazo': require('../../assets/img/musculos-mini/antebrazo.webp'),
  'biceps': require('../../assets/img/musculos-mini/biceps.webp'),
  'braquial': require('../../assets/img/musculos-mini/braquial.webp'),
  'buccinador': require('../../assets/img/musculos-mini/buccinador.webp'),
  'cigomaticos': require('../../assets/img/musculos-mini/cigomaticos.webp'),
  'core': require('../../assets/img/musculos-mini/core.webp'),
  'cuadriceps': require('../../assets/img/musculos-mini/cuadriceps.webp'),
  'cuello_flexores': require('../../assets/img/musculos-mini/cuello_flexores.webp'),
  'deltoide_anterior': require('../../assets/img/musculos-mini/deltoide_anterior.webp'),
  'deltoide_lateral': require('../../assets/img/musculos-mini/deltoide_lateral.webp'),
  'deltoide_posterior': require('../../assets/img/musculos-mini/deltoide_posterior.webp'),
  'depresor_labio': require('../../assets/img/musculos-mini/depresor_labio.webp'),
  'diafragma': require('../../assets/img/musculos-mini/diafragma.webp'),
  'digastrico': require('../../assets/img/musculos-mini/digastrico.webp'),
  'dorsal_ancho': require('../../assets/img/musculos-mini/dorsal_ancho.webp'),
  'erectores_espinales': require('../../assets/img/musculos-mini/erectores_espinales.webp'),
  'esternocleidomastoideo': require('../../assets/img/musculos-mini/esternocleidomastoideo.webp'),
  'extensores_cuello': require('../../assets/img/musculos-mini/extensores_cuello.webp'),
  'flexor_cadera': require('../../assets/img/musculos-mini/flexor_cadera.webp'),
  'gemelos': require('../../assets/img/musculos-mini/gemelos.webp'),
  'gluteo_mayor': require('../../assets/img/musculos-mini/gluteo_mayor.webp'),
  'gluteo_medio': require('../../assets/img/musculos-mini/gluteo_medio.webp'),
  'gluteo_menor': require('../../assets/img/musculos-mini/gluteo_menor.webp'),
  'isquiotibiales': require('../../assets/img/musculos-mini/isquiotibiales.webp'),
  'lengua': require('../../assets/img/musculos-mini/lengua.webp'),
  'manguito_rotador': require('../../assets/img/musculos-mini/manguito_rotador.webp'),
  'masetero': require('../../assets/img/musculos-mini/masetero.webp'),
  'multifidos': require('../../assets/img/musculos-mini/multifidos.webp'),
  'oblicuo_externo': require('../../assets/img/musculos-mini/oblicuo_externo.webp'),
  'oblicuo_interno': require('../../assets/img/musculos-mini/oblicuo_interno.webp'),
  'orbicular_labios': require('../../assets/img/musculos-mini/orbicular_labios.webp'),
  'pectoral_mayor': require('../../assets/img/musculos-mini/pectoral_mayor.webp'),
  'pectoral_menor': require('../../assets/img/musculos-mini/pectoral_menor.webp'),
  'pie_intrinsecos': require('../../assets/img/musculos-mini/pie_intrinsecos.webp'),
  'platisma': require('../../assets/img/musculos-mini/platisma.webp'),
  'pterigoideos': require('../../assets/img/musculos-mini/pterigoideos.webp'),
  'recto_abdominal': require('../../assets/img/musculos-mini/recto_abdominal.webp'),
  'recto_femoral': require('../../assets/img/musculos-mini/recto_femoral.webp'),
  'redondo_mayor': require('../../assets/img/musculos-mini/redondo_mayor.webp'),
  'romboides': require('../../assets/img/musculos-mini/romboides.webp'),
  'serrato_anterior': require('../../assets/img/musculos-mini/serrato_anterior.webp'),
  'soleo': require('../../assets/img/musculos-mini/soleo.webp'),
  'suelo_pelvico': require('../../assets/img/musculos-mini/suelo_pelvico.webp'),
  'temporal': require('../../assets/img/musculos-mini/temporal.webp'),
  'tensor_fascia_lata': require('../../assets/img/musculos-mini/tensor_fascia_lata.webp'),
  'tibial_anterior': require('../../assets/img/musculos-mini/tibial_anterior.webp'),
  'transverso_abdominal': require('../../assets/img/musculos-mini/transverso_abdominal.webp'),
  'trapecio_inferior': require('../../assets/img/musculos-mini/trapecio_inferior.webp'),
  'trapecio_medio': require('../../assets/img/musculos-mini/trapecio_medio.webp'),
  'trapecio_superior': require('../../assets/img/musculos-mini/trapecio_superior.webp'),
  'triceps': require('../../assets/img/musculos-mini/triceps.webp'),
};

export type TipoFoto = 'ejercicio' | 'musculo' | 'rutina' | 'programa' | 'tip' | 'mito' | 'fondo' | 'motivacion';

const MAPAS: Record<TipoFoto, Registro> = {
  ejercicio: IMG_EJERCICIOS,
  musculo: IMG_MUSCULOS,
  rutina: IMG_RUTINAS,
  programa: IMG_PROGRAMAS,
  tip: IMG_TIPS,
  mito: IMG_MITOS,
  fondo: IMG_FONDOS,
  motivacion: IMG_MOTIVACION,
};

const MINIS: Partial<Record<TipoFoto, Registro>> = {
  ejercicio: IMG_EJERCICIOS_MINI,
  musculo: IMG_MUSCULOS_MINI,
};

/** Fuente de una imagen, o null si el archivo todavia no esta. */
export function fuente(tipo: TipoFoto, id: string): number | null {
  return MAPAS[tipo][id] ?? null;
}

/** La miniatura de lista (lado corto de 192 px), o la imagen grande si ese tipo no tiene. */
export function fuenteMini(tipo: TipoFoto, id: string): number | null {
  return MINIS[tipo]?.[id] ?? fuente(tipo, id);
}
