/**
 * FORJA · registro de imagenes
 *
 * ARCHIVO GENERADO por generar_registry.py. No lo edites a mano: copia tus
 * imagenes a assets/img/<carpeta>/<id>.jpg y vuelve a correr el script.
 *
 * React Native no permite require() con ruta variable, por eso cada archivo
 * se declara aqui una vez. Lo que no este registrado se dibuja con un
 * marcador generado del id, asi que la app funciona con cero imagenes.
 *
 * La imagen del ejercicio hace doble funcion: miniatura en las listas y
 * poster del video mientras decodifica el primer fotograma. Por eso no hay
 * carpeta de thumbs.
 */

type Registro = Record<string, number>;


/* ejercicios · 190 */
const IMG_EJERCICIOS: Registro = {
  'ex_1001': require('../../assets/img/ejercicios/ex_1001.jpg'),
  'ex_1002': require('../../assets/img/ejercicios/ex_1002.jpg'),
  'ex_1003': require('../../assets/img/ejercicios/ex_1003.jpg'),
  'ex_1004': require('../../assets/img/ejercicios/ex_1004.jpg'),
  'ex_1005': require('../../assets/img/ejercicios/ex_1005.jpg'),
  'ex_1006': require('../../assets/img/ejercicios/ex_1006.jpg'),
  'ex_1007': require('../../assets/img/ejercicios/ex_1007.jpg'),
  'ex_1008': require('../../assets/img/ejercicios/ex_1008.jpg'),
  'ex_1009': require('../../assets/img/ejercicios/ex_1009.jpg'),
  'ex_1010': require('../../assets/img/ejercicios/ex_1010.jpg'),
  'ex_1011': require('../../assets/img/ejercicios/ex_1011.jpg'),
  'ex_1012': require('../../assets/img/ejercicios/ex_1012.jpg'),
  'ex_1013': require('../../assets/img/ejercicios/ex_1013.jpg'),
  'ex_1014': require('../../assets/img/ejercicios/ex_1014.jpg'),
  'ex_1015': require('../../assets/img/ejercicios/ex_1015.jpg'),
  'ex_1016': require('../../assets/img/ejercicios/ex_1016.jpg'),
  'ex_1017': require('../../assets/img/ejercicios/ex_1017.jpg'),
  'ex_1018': require('../../assets/img/ejercicios/ex_1018.jpg'),
  'ex_1019': require('../../assets/img/ejercicios/ex_1019.jpg'),
  'ex_1020': require('../../assets/img/ejercicios/ex_1020.jpg'),
  'ex_1021': require('../../assets/img/ejercicios/ex_1021.jpg'),
  'ex_1022': require('../../assets/img/ejercicios/ex_1022.jpg'),
  'ex_1023': require('../../assets/img/ejercicios/ex_1023.jpg'),
  'ex_1024': require('../../assets/img/ejercicios/ex_1024.jpg'),
  'ex_1025': require('../../assets/img/ejercicios/ex_1025.jpg'),
  'ex_1026': require('../../assets/img/ejercicios/ex_1026.jpg'),
  'ex_1027': require('../../assets/img/ejercicios/ex_1027.jpg'),
  'ex_1028': require('../../assets/img/ejercicios/ex_1028.jpg'),
  'ex_1029': require('../../assets/img/ejercicios/ex_1029.jpg'),
  'ex_1030': require('../../assets/img/ejercicios/ex_1030.jpg'),
  'ex_2001': require('../../assets/img/ejercicios/ex_2001.jpg'),
  'ex_2002': require('../../assets/img/ejercicios/ex_2002.jpg'),
  'ex_2003': require('../../assets/img/ejercicios/ex_2003.jpg'),
  'ex_2004': require('../../assets/img/ejercicios/ex_2004.jpg'),
  'ex_2005': require('../../assets/img/ejercicios/ex_2005.jpg'),
  'ex_2006': require('../../assets/img/ejercicios/ex_2006.jpg'),
  'ex_2007': require('../../assets/img/ejercicios/ex_2007.jpg'),
  'ex_2008': require('../../assets/img/ejercicios/ex_2008.jpg'),
  'ex_2009': require('../../assets/img/ejercicios/ex_2009.jpg'),
  'ex_2010': require('../../assets/img/ejercicios/ex_2010.jpg'),
  'ex_2011': require('../../assets/img/ejercicios/ex_2011.jpg'),
  'ex_2012': require('../../assets/img/ejercicios/ex_2012.jpg'),
  'ex_2013': require('../../assets/img/ejercicios/ex_2013.jpg'),
  'ex_2014': require('../../assets/img/ejercicios/ex_2014.jpg'),
  'ex_2015': require('../../assets/img/ejercicios/ex_2015.jpg'),
  'ex_2016': require('../../assets/img/ejercicios/ex_2016.jpg'),
  'ex_2017': require('../../assets/img/ejercicios/ex_2017.jpg'),
  'ex_2018': require('../../assets/img/ejercicios/ex_2018.jpg'),
  'ex_2019': require('../../assets/img/ejercicios/ex_2019.jpg'),
  'ex_2020': require('../../assets/img/ejercicios/ex_2020.jpg'),
  'ex_3001': require('../../assets/img/ejercicios/ex_3001.jpg'),
  'ex_3002': require('../../assets/img/ejercicios/ex_3002.jpg'),
  'ex_3003': require('../../assets/img/ejercicios/ex_3003.jpg'),
  'ex_3004': require('../../assets/img/ejercicios/ex_3004.jpg'),
  'ex_3005': require('../../assets/img/ejercicios/ex_3005.jpg'),
  'ex_3006': require('../../assets/img/ejercicios/ex_3006.jpg'),
  'ex_3007': require('../../assets/img/ejercicios/ex_3007.jpg'),
  'ex_3008': require('../../assets/img/ejercicios/ex_3008.jpg'),
  'ex_3009': require('../../assets/img/ejercicios/ex_3009.jpg'),
  'ex_3010': require('../../assets/img/ejercicios/ex_3010.jpg'),
  'ex_3011': require('../../assets/img/ejercicios/ex_3011.jpg'),
  'ex_3012': require('../../assets/img/ejercicios/ex_3012.jpg'),
  'ex_3013': require('../../assets/img/ejercicios/ex_3013.jpg'),
  'ex_3014': require('../../assets/img/ejercicios/ex_3014.jpg'),
  'ex_3015': require('../../assets/img/ejercicios/ex_3015.jpg'),
  'ex_3016': require('../../assets/img/ejercicios/ex_3016.jpg'),
  'ex_3017': require('../../assets/img/ejercicios/ex_3017.jpg'),
  'ex_3018': require('../../assets/img/ejercicios/ex_3018.jpg'),
  'ex_3019': require('../../assets/img/ejercicios/ex_3019.jpg'),
  'ex_3020': require('../../assets/img/ejercicios/ex_3020.jpg'),
  'ex_4001': require('../../assets/img/ejercicios/ex_4001.jpg'),
  'ex_4002': require('../../assets/img/ejercicios/ex_4002.jpg'),
  'ex_4003': require('../../assets/img/ejercicios/ex_4003.jpg'),
  'ex_4004': require('../../assets/img/ejercicios/ex_4004.jpg'),
  'ex_4005': require('../../assets/img/ejercicios/ex_4005.jpg'),
  'ex_4006': require('../../assets/img/ejercicios/ex_4006.jpg'),
  'ex_4007': require('../../assets/img/ejercicios/ex_4007.jpg'),
  'ex_4008': require('../../assets/img/ejercicios/ex_4008.jpg'),
  'ex_4009': require('../../assets/img/ejercicios/ex_4009.jpg'),
  'ex_4010': require('../../assets/img/ejercicios/ex_4010.jpg'),
  'ex_4011': require('../../assets/img/ejercicios/ex_4011.jpg'),
  'ex_4012': require('../../assets/img/ejercicios/ex_4012.jpg'),
  'ex_4013': require('../../assets/img/ejercicios/ex_4013.jpg'),
  'ex_4014': require('../../assets/img/ejercicios/ex_4014.jpg'),
  'ex_4015': require('../../assets/img/ejercicios/ex_4015.jpg'),
  'ex_4016': require('../../assets/img/ejercicios/ex_4016.jpg'),
  'ex_4017': require('../../assets/img/ejercicios/ex_4017.jpg'),
  'ex_4018': require('../../assets/img/ejercicios/ex_4018.jpg'),
  'ex_4019': require('../../assets/img/ejercicios/ex_4019.jpg'),
  'ex_4020': require('../../assets/img/ejercicios/ex_4020.jpg'),
  'ex_4021': require('../../assets/img/ejercicios/ex_4021.jpg'),
  'ex_4022': require('../../assets/img/ejercicios/ex_4022.jpg'),
  'ex_5001': require('../../assets/img/ejercicios/ex_5001.jpg'),
  'ex_5002': require('../../assets/img/ejercicios/ex_5002.jpg'),
  'ex_5003': require('../../assets/img/ejercicios/ex_5003.jpg'),
  'ex_5004': require('../../assets/img/ejercicios/ex_5004.jpg'),
  'ex_5005': require('../../assets/img/ejercicios/ex_5005.jpg'),
  'ex_5006': require('../../assets/img/ejercicios/ex_5006.jpg'),
  'ex_5007': require('../../assets/img/ejercicios/ex_5007.jpg'),
  'ex_5008': require('../../assets/img/ejercicios/ex_5008.jpg'),
  'ex_5009': require('../../assets/img/ejercicios/ex_5009.jpg'),
  'ex_5010': require('../../assets/img/ejercicios/ex_5010.jpg'),
  'ex_5011': require('../../assets/img/ejercicios/ex_5011.jpg'),
  'ex_5012': require('../../assets/img/ejercicios/ex_5012.jpg'),
  'ex_5013': require('../../assets/img/ejercicios/ex_5013.jpg'),
  'ex_5014': require('../../assets/img/ejercicios/ex_5014.jpg'),
  'ex_5015': require('../../assets/img/ejercicios/ex_5015.jpg'),
  'ex_5016': require('../../assets/img/ejercicios/ex_5016.jpg'),
  'ex_5017': require('../../assets/img/ejercicios/ex_5017.jpg'),
  'ex_5018': require('../../assets/img/ejercicios/ex_5018.jpg'),
  'ex_5019': require('../../assets/img/ejercicios/ex_5019.jpg'),
  'ex_5020': require('../../assets/img/ejercicios/ex_5020.jpg'),
  'ex_5101': require('../../assets/img/ejercicios/ex_5101.jpg'),
  'ex_5102': require('../../assets/img/ejercicios/ex_5102.jpg'),
  'ex_5103': require('../../assets/img/ejercicios/ex_5103.jpg'),
  'ex_5104': require('../../assets/img/ejercicios/ex_5104.jpg'),
  'ex_5105': require('../../assets/img/ejercicios/ex_5105.jpg'),
  'ex_5106': require('../../assets/img/ejercicios/ex_5106.jpg'),
  'ex_5107': require('../../assets/img/ejercicios/ex_5107.jpg'),
  'ex_5108': require('../../assets/img/ejercicios/ex_5108.jpg'),
  'ex_5109': require('../../assets/img/ejercicios/ex_5109.jpg'),
  'ex_5110': require('../../assets/img/ejercicios/ex_5110.jpg'),
  'ex_5111': require('../../assets/img/ejercicios/ex_5111.jpg'),
  'ex_6101': require('../../assets/img/ejercicios/ex_6101.jpg'),
  'ex_6102': require('../../assets/img/ejercicios/ex_6102.jpg'),
  'ex_6103': require('../../assets/img/ejercicios/ex_6103.jpg'),
  'ex_6104': require('../../assets/img/ejercicios/ex_6104.jpg'),
  'ex_6105': require('../../assets/img/ejercicios/ex_6105.jpg'),
  'ex_6106': require('../../assets/img/ejercicios/ex_6106.jpg'),
  'ex_6107': require('../../assets/img/ejercicios/ex_6107.jpg'),
  'ex_6108': require('../../assets/img/ejercicios/ex_6108.jpg'),
  'ex_6109': require('../../assets/img/ejercicios/ex_6109.jpg'),
  'ex_6110': require('../../assets/img/ejercicios/ex_6110.jpg'),
  'ex_6111': require('../../assets/img/ejercicios/ex_6111.jpg'),
  'ex_6112': require('../../assets/img/ejercicios/ex_6112.jpg'),
  'ex_6113': require('../../assets/img/ejercicios/ex_6113.jpg'),
  'ex_6114': require('../../assets/img/ejercicios/ex_6114.jpg'),
  'ex_6115': require('../../assets/img/ejercicios/ex_6115.jpg'),
  'ex_6116': require('../../assets/img/ejercicios/ex_6116.jpg'),
  'ex_6117': require('../../assets/img/ejercicios/ex_6117.jpg'),
  'ex_6118': require('../../assets/img/ejercicios/ex_6118.jpg'),
  'ex_6119': require('../../assets/img/ejercicios/ex_6119.jpg'),
  'ex_6120': require('../../assets/img/ejercicios/ex_6120.jpg'),
  'ex_6501': require('../../assets/img/ejercicios/ex_6501.jpg'),
  'ex_6502': require('../../assets/img/ejercicios/ex_6502.jpg'),
  'ex_6503': require('../../assets/img/ejercicios/ex_6503.jpg'),
  'ex_6504': require('../../assets/img/ejercicios/ex_6504.jpg'),
  'ex_6505': require('../../assets/img/ejercicios/ex_6505.jpg'),
  'ex_6506': require('../../assets/img/ejercicios/ex_6506.jpg'),
  'ex_6507': require('../../assets/img/ejercicios/ex_6507.jpg'),
  'ex_6508': require('../../assets/img/ejercicios/ex_6508.jpg'),
  'ex_6509': require('../../assets/img/ejercicios/ex_6509.jpg'),
  'ex_6510': require('../../assets/img/ejercicios/ex_6510.jpg'),
  'ex_6511': require('../../assets/img/ejercicios/ex_6511.jpg'),
  'ex_6512': require('../../assets/img/ejercicios/ex_6512.jpg'),
  'ex_7001': require('../../assets/img/ejercicios/ex_7001.jpg'),
  'ex_7002': require('../../assets/img/ejercicios/ex_7002.jpg'),
  'ex_7003': require('../../assets/img/ejercicios/ex_7003.jpg'),
  'ex_7004': require('../../assets/img/ejercicios/ex_7004.jpg'),
  'ex_7005': require('../../assets/img/ejercicios/ex_7005.jpg'),
  'ex_7006': require('../../assets/img/ejercicios/ex_7006.jpg'),
  'ex_7007': require('../../assets/img/ejercicios/ex_7007.jpg'),
  'ex_7008': require('../../assets/img/ejercicios/ex_7008.jpg'),
  'ex_7009': require('../../assets/img/ejercicios/ex_7009.jpg'),
  'ex_7010': require('../../assets/img/ejercicios/ex_7010.jpg'),
  'ex_7011': require('../../assets/img/ejercicios/ex_7011.jpg'),
  'ex_7012': require('../../assets/img/ejercicios/ex_7012.jpg'),
  'ex_7013': require('../../assets/img/ejercicios/ex_7013.jpg'),
  'ex_7014': require('../../assets/img/ejercicios/ex_7014.jpg'),
  'ex_7015': require('../../assets/img/ejercicios/ex_7015.jpg'),
  'ex_7016': require('../../assets/img/ejercicios/ex_7016.jpg'),
  'ex_7017': require('../../assets/img/ejercicios/ex_7017.jpg'),
  'ex_7018': require('../../assets/img/ejercicios/ex_7018.jpg'),
  'ex_7019': require('../../assets/img/ejercicios/ex_7019.jpg'),
  'ex_7020': require('../../assets/img/ejercicios/ex_7020.jpg'),
  'ex_8001': require('../../assets/img/ejercicios/ex_8001.jpg'),
  'ex_8002': require('../../assets/img/ejercicios/ex_8002.jpg'),
  'ex_8003': require('../../assets/img/ejercicios/ex_8003.jpg'),
  'ex_8004': require('../../assets/img/ejercicios/ex_8004.jpg'),
  'ex_8005': require('../../assets/img/ejercicios/ex_8005.jpg'),
  'ex_8006': require('../../assets/img/ejercicios/ex_8006.jpg'),
  'ex_8007': require('../../assets/img/ejercicios/ex_8007.jpg'),
  'ex_8008': require('../../assets/img/ejercicios/ex_8008.jpg'),
  'ex_8009': require('../../assets/img/ejercicios/ex_8009.jpg'),
  'ex_8010': require('../../assets/img/ejercicios/ex_8010.jpg'),
  'ex_8011': require('../../assets/img/ejercicios/ex_8011.jpg'),
  'ex_8012': require('../../assets/img/ejercicios/ex_8012.jpg'),
  'ex_8013': require('../../assets/img/ejercicios/ex_8013.jpg'),
  'ex_8014': require('../../assets/img/ejercicios/ex_8014.jpg'),
  'ex_8015': require('../../assets/img/ejercicios/ex_8015.jpg'),
};

/* musculos · 53 */
const IMG_MUSCULOS: Registro = {
  'aductores': require('../../assets/img/musculos/aductores.jpg'),
  'antebrazo': require('../../assets/img/musculos/antebrazo.jpg'),
  'biceps': require('../../assets/img/musculos/biceps.jpg'),
  'braquial': require('../../assets/img/musculos/braquial.jpg'),
  'buccinador': require('../../assets/img/musculos/buccinador.jpg'),
  'cigomaticos': require('../../assets/img/musculos/cigomaticos.jpg'),
  'core': require('../../assets/img/musculos/core.jpg'),
  'cuadriceps': require('../../assets/img/musculos/cuadriceps.jpg'),
  'cuello_flexores': require('../../assets/img/musculos/cuello_flexores.jpg'),
  'deltoide_anterior': require('../../assets/img/musculos/deltoide_anterior.jpg'),
  'deltoide_lateral': require('../../assets/img/musculos/deltoide_lateral.jpg'),
  'deltoide_posterior': require('../../assets/img/musculos/deltoide_posterior.jpg'),
  'deltoide_posterior.': require('../../assets/img/musculos/deltoide_posterior..jpg'),
  'depresor_labio': require('../../assets/img/musculos/depresor_labio.jpg'),
  'diafragma': require('../../assets/img/musculos/diafragma.jpg'),
  'digastrico': require('../../assets/img/musculos/digastrico.jpg'),
  'dorsal_ancho': require('../../assets/img/musculos/dorsal_ancho.jpg'),
  'erectores_espinales': require('../../assets/img/musculos/erectores_espinales.jpg'),
  'esternocleidomastoideo': require('../../assets/img/musculos/esternocleidomastoideo.jpg'),
  'extensores_cuello': require('../../assets/img/musculos/extensores_cuello.jpg'),
  'flexor_cadera': require('../../assets/img/musculos/flexor_cadera.jpg'),
  'gemelos': require('../../assets/img/musculos/gemelos.jpg'),
  'gluteo_mayor': require('../../assets/img/musculos/gluteo_mayor.jpg'),
  'gluteo_medio': require('../../assets/img/musculos/gluteo_medio.jpg'),
  'gluteo_menor': require('../../assets/img/musculos/gluteo_menor.jpg'),
  'isquiotibiales': require('../../assets/img/musculos/isquiotibiales.jpg'),
  'lengua': require('../../assets/img/musculos/lengua.jpg'),
  'manguito_rotador': require('../../assets/img/musculos/manguito_rotador.jpg'),
  'masetero': require('../../assets/img/musculos/masetero.jpg'),
  'multifidos': require('../../assets/img/musculos/multifidos.jpg'),
  'oblicuo_externo': require('../../assets/img/musculos/oblicuo_externo.jpg'),
  'oblicuo_interno': require('../../assets/img/musculos/oblicuo_interno.jpg'),
  'orbicular_labios': require('../../assets/img/musculos/orbicular_labios.jpg'),
  'pectoral_mayor': require('../../assets/img/musculos/pectoral_mayor.jpg'),
  'pectoral_menor': require('../../assets/img/musculos/pectoral_menor.jpg'),
  'pie_intrinsecos': require('../../assets/img/musculos/pie_intrinsecos.jpg'),
  'platisma': require('../../assets/img/musculos/platisma.jpg'),
  'pterigoideos': require('../../assets/img/musculos/pterigoideos.jpg'),
  'recto_abdominal': require('../../assets/img/musculos/recto_abdominal.jpg'),
  'recto_femoral': require('../../assets/img/musculos/recto_femoral.jpg'),
  'redondo_mayor': require('../../assets/img/musculos/redondo_mayor.jpg'),
  'romboides': require('../../assets/img/musculos/romboides.jpg'),
  'serrato_anterior': require('../../assets/img/musculos/serrato_anterior.jpg'),
  'soleo': require('../../assets/img/musculos/soleo.jpg'),
  'suelo_pelvico': require('../../assets/img/musculos/suelo_pelvico.jpg'),
  'temporal': require('../../assets/img/musculos/temporal.jpg'),
  'tensor_fascia_lata': require('../../assets/img/musculos/tensor_fascia_lata.jpg'),
  'tibial_anterior': require('../../assets/img/musculos/tibial_anterior.jpg'),
  'transverso_abdominal': require('../../assets/img/musculos/transverso_abdominal.jpg'),
  'trapecio_inferior': require('../../assets/img/musculos/trapecio_inferior.jpg'),
  'trapecio_medio': require('../../assets/img/musculos/trapecio_medio.jpg'),
  'trapecio_superior': require('../../assets/img/musculos/trapecio_superior.jpg'),
  'triceps': require('../../assets/img/musculos/triceps.jpg'),
};

/* rutinas · 30 */
const IMG_RUTINAS: Registro = {
  'rt_001': require('../../assets/img/rutinas/rt_001.jpg'),
  'rt_002': require('../../assets/img/rutinas/rt_002.jpg'),
  'rt_003': require('../../assets/img/rutinas/rt_003.jpg'),
  'rt_004': require('../../assets/img/rutinas/rt_004.jpg'),
  'rt_005': require('../../assets/img/rutinas/rt_005.jpg'),
  'rt_006': require('../../assets/img/rutinas/rt_006.jpg'),
  'rt_007': require('../../assets/img/rutinas/rt_007.jpg'),
  'rt_008': require('../../assets/img/rutinas/rt_008.jpg'),
  'rt_009': require('../../assets/img/rutinas/rt_009.jpg'),
  'rt_010': require('../../assets/img/rutinas/rt_010.jpg'),
  'rt_011': require('../../assets/img/rutinas/rt_011.jpg'),
  'rt_012': require('../../assets/img/rutinas/rt_012.jpg'),
  'rt_013': require('../../assets/img/rutinas/rt_013.jpg'),
  'rt_014': require('../../assets/img/rutinas/rt_014.jpg'),
  'rt_015': require('../../assets/img/rutinas/rt_015.jpg'),
  'rt_016': require('../../assets/img/rutinas/rt_016.jpg'),
  'rt_017': require('../../assets/img/rutinas/rt_017.jpg'),
  'rt_018': require('../../assets/img/rutinas/rt_018.jpg'),
  'rt_019': require('../../assets/img/rutinas/rt_019.jpg'),
  'rt_020': require('../../assets/img/rutinas/rt_020.jpg'),
  'rt_021': require('../../assets/img/rutinas/rt_021.jpg'),
  'rt_022': require('../../assets/img/rutinas/rt_022.jpg'),
  'rt_023': require('../../assets/img/rutinas/rt_023.jpg'),
  'rt_024': require('../../assets/img/rutinas/rt_024.jpg'),
  'rt_025': require('../../assets/img/rutinas/rt_025.jpg'),
  'rt_026': require('../../assets/img/rutinas/rt_026.jpg'),
  'rt_027': require('../../assets/img/rutinas/rt_027.jpg'),
  'rt_028': require('../../assets/img/rutinas/rt_028.jpg'),
  'rt_029': require('../../assets/img/rutinas/rt_029.jpg'),
  'rt_030': require('../../assets/img/rutinas/rt_030.jpg'),
};

/* programas · 12 */
const IMG_PROGRAMAS: Registro = {
  'pg_001': require('../../assets/img/programas/pg_001.jpg'),
  'pg_002': require('../../assets/img/programas/pg_002.jpg'),
  'pg_003': require('../../assets/img/programas/pg_003.jpg'),
  'pg_004': require('../../assets/img/programas/pg_004.jpg'),
  'pg_005': require('../../assets/img/programas/pg_005.jpg'),
  'pg_006': require('../../assets/img/programas/pg_006.jpg'),
  'pg_007': require('../../assets/img/programas/pg_007.jpg'),
  'pg_008': require('../../assets/img/programas/pg_008.jpg'),
  'pg_009': require('../../assets/img/programas/pg_009.jpg'),
  'pg_010': require('../../assets/img/programas/pg_010.jpg'),
  'pg_011': require('../../assets/img/programas/pg_011.jpg'),
  'pg_012': require('../../assets/img/programas/pg_012.jpg'),
};

/* tips · 52 */
const IMG_TIPS: Registro = {
  'nut_001': require('../../assets/img/tips/nut_001.jpg'),
  'nut_002': require('../../assets/img/tips/nut_002.jpg'),
  'nut_003': require('../../assets/img/tips/nut_003.jpg'),
  'nut_004': require('../../assets/img/tips/nut_004.jpg'),
  'nut_005': require('../../assets/img/tips/nut_005.jpg'),
  'nut_006': require('../../assets/img/tips/nut_006.jpg'),
  'nut_007': require('../../assets/img/tips/nut_007.jpg'),
  'nut_009': require('../../assets/img/tips/nut_009.jpg'),
  'nut_010': require('../../assets/img/tips/nut_010.jpg'),
  'nut_011': require('../../assets/img/tips/nut_011.jpg'),
  'nut_012': require('../../assets/img/tips/nut_012.jpg'),
  'nut_013': require('../../assets/img/tips/nut_013.jpg'),
  'nut_014': require('../../assets/img/tips/nut_014.jpg'),
  'nut_015': require('../../assets/img/tips/nut_015.jpg'),
  'tip_001': require('../../assets/img/tips/tip_001.jpg'),
  'tip_002': require('../../assets/img/tips/tip_002.jpg'),
  'tip_003': require('../../assets/img/tips/tip_003.jpg'),
  'tip_004': require('../../assets/img/tips/tip_004.jpg'),
  'tip_005': require('../../assets/img/tips/tip_005.jpg'),
  'tip_006': require('../../assets/img/tips/tip_006.jpg'),
  'tip_007': require('../../assets/img/tips/tip_007.jpg'),
  'tip_008': require('../../assets/img/tips/tip_008.jpg'),
  'tip_009': require('../../assets/img/tips/tip_009.jpg'),
  'tip_010': require('../../assets/img/tips/tip_010.jpg'),
  'tip_011': require('../../assets/img/tips/tip_011.jpg'),
  'tip_012': require('../../assets/img/tips/tip_012.jpg'),
  'tip_013': require('../../assets/img/tips/tip_013.jpg'),
  'tip_014': require('../../assets/img/tips/tip_014.jpg'),
  'tip_015': require('../../assets/img/tips/tip_015.jpg'),
  'tip_016': require('../../assets/img/tips/tip_016.jpg'),
  'tip_017': require('../../assets/img/tips/tip_017.jpg'),
  'tip_018': require('../../assets/img/tips/tip_018.jpg'),
  'tip_019': require('../../assets/img/tips/tip_019.jpg'),
  'tip_020': require('../../assets/img/tips/tip_020.jpg'),
  'tip_021': require('../../assets/img/tips/tip_021.jpg'),
  'tip_022': require('../../assets/img/tips/tip_022.jpg'),
  'tip_023': require('../../assets/img/tips/tip_023.jpg'),
  'tip_024': require('../../assets/img/tips/tip_024.jpg'),
  'tip_025': require('../../assets/img/tips/tip_025.jpg'),
  'tip_026': require('../../assets/img/tips/tip_026.jpg'),
  'tip_027': require('../../assets/img/tips/tip_027.jpg'),
  'tip_028': require('../../assets/img/tips/tip_028.jpg'),
  'tip_029': require('../../assets/img/tips/tip_029.jpg'),
  'tip_030': require('../../assets/img/tips/tip_030.jpg'),
  'tip_031': require('../../assets/img/tips/tip_031.jpg'),
  'tip_032': require('../../assets/img/tips/tip_032.jpg'),
  'tip_033': require('../../assets/img/tips/tip_033.jpg'),
  'tip_034': require('../../assets/img/tips/tip_034.jpg'),
  'tip_035': require('../../assets/img/tips/tip_035.jpg'),
  'tip_036': require('../../assets/img/tips/tip_036.jpg'),
  'tip_037': require('../../assets/img/tips/tip_037.jpg'),
  'tip_038': require('../../assets/img/tips/tip_038.jpg'),
};

/* mitos · 20 */
const IMG_MITOS: Registro = {
  'myth_001': require('../../assets/img/mitos/myth_001.jpg'),
  'myth_002': require('../../assets/img/mitos/myth_002.jpg'),
  'myth_003': require('../../assets/img/mitos/myth_003.jpg'),
  'myth_004': require('../../assets/img/mitos/myth_004.jpg'),
  'myth_005': require('../../assets/img/mitos/myth_005.jpg'),
  'myth_006': require('../../assets/img/mitos/myth_006.jpg'),
  'myth_007': require('../../assets/img/mitos/myth_007.jpg'),
  'myth_008': require('../../assets/img/mitos/myth_008.jpg'),
  'myth_009': require('../../assets/img/mitos/myth_009.jpg'),
  'myth_010': require('../../assets/img/mitos/myth_010.jpg'),
  'myth_011': require('../../assets/img/mitos/myth_011.jpg'),
  'myth_012': require('../../assets/img/mitos/myth_012.jpg'),
  'myth_013': require('../../assets/img/mitos/myth_013.jpg'),
  'myth_014': require('../../assets/img/mitos/myth_014.jpg'),
  'myth_015': require('../../assets/img/mitos/myth_015.jpg'),
  'myth_016': require('../../assets/img/mitos/myth_016.jpg'),
  'myth_017': require('../../assets/img/mitos/myth_017.jpg'),
  'myth_018': require('../../assets/img/mitos/myth_018.jpg'),
  'myth_019': require('../../assets/img/mitos/myth_019.jpg'),
  'myth_020': require('../../assets/img/mitos/myth_020.jpg'),
};

/* motivacion · 21 */
const IMG_MOTIVACION: Registro = {
  'mot_01': require('../../assets/img/motivacion/mot_01.jpg'),
  'mot_02': require('../../assets/img/motivacion/mot_02.jpg'),
  'mot_03': require('../../assets/img/motivacion/mot_03.jpg'),
  'mot_04': require('../../assets/img/motivacion/mot_04.jpg'),
  'mot_05': require('../../assets/img/motivacion/mot_05.jpg'),
  'mot_06': require('../../assets/img/motivacion/mot_06.jpg'),
  'mot_07': require('../../assets/img/motivacion/mot_07.jpg'),
  'mot_08': require('../../assets/img/motivacion/mot_08.jpg'),
  'mot_09': require('../../assets/img/motivacion/mot_09.jpg'),
  'mot_10': require('../../assets/img/motivacion/mot_10.jpg'),
  'mot_11': require('../../assets/img/motivacion/mot_11.jpg'),
  'mot_12': require('../../assets/img/motivacion/mot_12.jpg'),
  'mot_13': require('../../assets/img/motivacion/mot_13.jpg'),
  'mot_14': require('../../assets/img/motivacion/mot_14.jpg'),
  'mot_15': require('../../assets/img/motivacion/mot_15.jpg'),
  'mot_16': require('../../assets/img/motivacion/mot_16.jpg'),
  'mot_17': require('../../assets/img/motivacion/mot_17.jpg'),
  'mot_18': require('../../assets/img/motivacion/mot_18.jpg'),
  'mot_19': require('../../assets/img/motivacion/mot_19.jpg'),
  'mot_20': require('../../assets/img/motivacion/mot_20.jpg'),
  'mot_21': require('../../assets/img/motivacion/mot_21.jpg'),
};

/* fondos · 5 */
const IMG_FONDOS: Registro = {
  'bienvenida': require('../../assets/img/fondos/bienvenida.jpg'),
  'intro_01': require('../../assets/img/fondos/intro_01.jpg'),
  'intro_02': require('../../assets/img/fondos/intro_02.jpg'),
  'intro_03': require('../../assets/img/fondos/intro_03.jpg'),
  'intro_04': require('../../assets/img/fondos/intro_04.jpg'),
};

export type TipoFoto = 'ejercicio' | 'musculo' | 'rutina' | 'programa' | 'tip' | 'mito' | 'fondo' | 'motivacion';

const MAPAS: Record<TipoFoto, Registro> = {
  ejercicio: IMG_EJERCICIOS,
  musculo: IMG_MUSCULOS,
  rutina: IMG_RUTINAS,
  programa: IMG_PROGRAMAS,
  tip: IMG_TIPS,
  mito: IMG_MITOS,
  fondo: IMG_FONDOS,
  motivacion: IMG_MOTIVACION,
};

/** Fuente de una imagen, o null si el archivo todavia no esta. */
export function fuente(tipo: TipoFoto, id: string): number | null {
  return MAPAS[tipo][id] ?? null;
}
